// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3vVXkAod0NXs-7KrQ8ISdXr2tDEXKSJw',
    appId: '1:9438506017:web:48cd56002aed1e6c698760',
    messagingSenderId: '9438506017',
    projectId: 'ton-tasks',
    authDomain: 'ton-tasks.firebaseapp.com',
    storageBucket: 'ton-tasks.appspot.com',
    measurementId: 'G-YLJ31NEXXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7S0UeUizvFBZo-SDSoWf7FQXy416NmUs',
    appId: '1:9438506017:android:5337524d1177fa88698760',
    messagingSenderId: '9438506017',
    projectId: 'ton-tasks',
    storageBucket: 'ton-tasks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeBhrQ6GHXbeDcrbKM5TEppXT1soarrkE',
    appId: '1:9438506017:ios:7a438ea18d0a9a5b698760',
    messagingSenderId: '9438506017',
    projectId: 'ton-tasks',
    storageBucket: 'ton-tasks.appspot.com',
    iosBundleId: 'com.nezam.tasks.nezam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeBhrQ6GHXbeDcrbKM5TEppXT1soarrkE',
    appId: '1:9438506017:ios:380385eece163bb3698760',
    messagingSenderId: '9438506017',
    projectId: 'ton-tasks',
    storageBucket: 'ton-tasks.appspot.com',
    iosBundleId: 'com.nezam.tasks.nezam.RunnerTests',
  );
}
